# Global toggle to enable/disable the chart
enabled: true

# Image settings
image:
  repository: docker.io/arconixforge/mongodb-secure-backup
  tag: v1.1
  pullPolicy: IfNotPresent

# Security context settings
securityContext:
  pod:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  container:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

# Storage configuration for backups
persistence:
  enabled: true
  storageClass: "standard-rwo"  # GKE standard storage class
  accessMode: ReadWriteOnce
  size: 20Gi
  annotations: {}

# RBAC settings
rbac:
  create: true

# MongoDB connection settings
connection:
  host: "mongodb-headless.mdb.svc.cluster.local"
  port: 27017
  username: "root"
  password: "password123"
  authDb: admin
  useSSL: false
  sslCAFile: ""
  connectionTimeoutMs: 30000



# Filter parameters
filters:
  excludeDbs: "admin,local"
  excludeCollections: "system.*"

# Security parameters
security:
  encryptionEnabled: true
  encryptionPassword: "password123"  # Should be set via Secret in production
  compressionMethod: lzma  # none, zlib, gzip, or lzma
  compressionLevel: 9  # 1 (fastest) to 9 (best compression)

# Backup tool specific options
backupTool:
  saveDbInfo: true       # Step 1: Save database metadata
  exportDatabases: true  # Step 2: Export databases to JSON
  createArchive: true    # Step 3: Create encrypted archives
  deleteOriginal: false  # Whether to delete original exports after archiving

# Export parameters
export:
  output_dir: "/backup-data/db-exports"  # Directory for database exports
  db_info_dir: "/backup-data/db-info"    # Directory for database info files
  archive_dir: "/backup-data/archives"   # Directory for encrypted archives
  prettyJson: true
  maxConcurrentExports: 3
  retryAttempts: 3
  retryDelaySeconds: 2
  chunkSize: 1000


# UI configuration
ui:
  enabled: false  # Set to true if you want to deploy the UI component
  image:
    repository: arconixforge/mongodb-backup-ui
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Backup schedule (using CronJob)
schedule:
  enabled: true
  # Run daily at 1:00 AM
  # cronExpression: "0 1 * * *" 12:11PM 
  cronExpression: "41 6 * * *" 
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid  # Allow, Forbid, or Replace
  backoffLimit: 3
  # Timeout for the backup job (in seconds)
  activeDeadlineSeconds: 3600  # 1 hour

# Resource requests and limits for GKE
resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Node scheduling for GKE
nodeSelector: {}
tolerations: []
affinity: {}

# Optional network policy
networkPolicy:
  enabled: false
  # If enabled, only pods with the specified label can connect to MongoDB
  # This is useful to restrict traffic to only the backup job
  podSelector:
    matchLabels:
      role: mongodb-backup

# Log settings
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  format: "[%(asctime)s] [%(levelname)s] %(message)s"