# charts/mongodb-secure-backup/templates/helpers-configmap.yaml
{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-backup.name" . }}-helpers
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
data:
  list-archives.sh: |
    #!/bin/bash
    echo "Available MongoDB Backup Archives:"
    ls -la {{ .Values.export.archiveDir }}/*.mdb 2>/dev/null || echo "No archives found"
    
  restore-archive.sh: |
    #!/bin/bash
    if [ "$#" -ne 1 ]; then
      echo "Usage: $0 <archive-filename>"
      echo "Example: $0 mongodb_backup_20250327_120000.mdb"
      exit 1
    fi
    
    ARCHIVE="{{ .Values.export.archiveDir }}/$1"
    if [ ! -f "$ARCHIVE" ]; then
      echo "Archive file not found: $ARCHIVE"
      exit 1
    fi
    
    echo "Restoring from archive: $ARCHIVE"
    python /app/mongodb_backup.py --config /tmp/config/mongodb_backup.ini --restore-archive "$ARCHIVE"
{{- end }}