{{- if and .Values.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mongodb-backup.name" . }}
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mongodb-backup.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  # Allow inbound traffic from specified pods
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.podSelector.matchLabels | nindent 14 }}
  # Allow outbound traffic to MongoDB and DNS
  egress:
    # MongoDB
    - to:
        - ipBlock:
            cidr: {{ .Values.connection.host }}/32
      ports:
        - protocol: TCP
          port: {{ .Values.connection.port }}
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}