{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-backup.name" . }}-secret
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.connection.password }}
  MONGO_PASSWORD: {{ .Values.connection.password | quote }}
  {{- end }}
  {{- if .Values.security.encryptionEnabled }}
  ENCRYPTION_PASSWORD: {{ .Values.security.encryptionPassword | default (randAlphaNum 16) | quote }}
  {{- end }}
{{- end }}