{{- if and .Values.enabled (hasKey .Values "ui") (hasKey .Values.ui "enabled") .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-backup.name" . }}-ui
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mongodb-backup.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}