{{- if and .Values.enabled .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb-backup.name" . }}
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
{{- end }}